---
title: "poster visualizations"
output: html_notebook
---

poster visualizations


mutated genes venn diagram
```{r}
library(nVennR)

nonas <- function(x) {unlist(as.list(na.exclude(x)))}

myV2 <- plotVenn(list(X=unique(c(nonas(df$X1), nonas(df$X2), nonas(df$X3))),  P=unique(c(nonas(df$P1), nonas(df$P2), nonas(df$P3))), T=unique(c(nonas(df$T1), nonas(df$T2), nonas(df$T3)))), nCycles = 20)
myV2 <- plotVenn(nVennObj = myV2, outFile="../Out/test_Venn.svg")

showSVG(nVennObj = myV2, opacity = 0.1, borderWidth = 3)

```
read in data
```{r}
library(readr)
genes_list <- read_csv("../Out/list_mutated_genes_SA6850_phenotype.csv")
```

```{r}

set_cluster_1 = genes_list%>%
                          filter(Cluster == 1)%>%
                          select(Mutated_gene)
set_cluster_2_SA = genes_list%>%
                          filter(Cluster == 2 & Condition == "S")%>%
                          select(Mutated_gene)
set_cluster_2_tsb = genes_list%>%
                          filter(Cluster == 2 & Condition == "T")%>%
                          select(Mutated_gene)
set_cluster_2_both = genes_list%>%
                          filter(Cluster == 2 & Condition == "T/S")%>%
                          select(Mutated_gene)
set_cluster_2 = genes_list%>%
                          filter(Cluster == 2)%>%
                          select(Mutated_gene)


myVenn <- plotVenn(sets = list(Cluster_1 = set_cluster_1, Cluster_2 = set_cluster_2, Cluster_2_tsb = set_cluster_2_tsb, Cluster_2_SA = set_cluster_2_SA, Cluster_2_both = set_cluster_2_both
                        ),
                   sNames = list(c("Cluster 1", "Cluster 2")),
                   outFile="../Out/test_Venn.svg"
)
```


```{r}

#Cluster 1 (21):
30,None,17802-19769:[6, {'JE2_T_D08_1': 1, 'JE2_T_D08_2': 1, 'JE2_T_D08_3': 1, 'JE2_T_F10_2': 1, 'JE2_T_F10_4': 1, 'JE2_T_F10_5': 1}]
250,None,128392-129918:[3, {'JE2_T_D10_1': 1, 'JE2_T_D10_3': 1, 'JE2_T_D10_5': 1}]
442,None,233920-235032:[1, {'JE2_T_D08_2': 1}]
1060,None,531927-532751:[1, {'JE2_T_D08_3': 1}]
1474,None,723018-723815:[1, {'JE2_T_D08_1': 1}]
1620,None,789860-790570:[1, {'JE2_T_F04_5': 1}]
2041,None,980328-981197:[1, {'JE2_T_D10_1': 1}]
2171,None,1042228-1043709:[4, {'JE2_T_D10_1': 1, 'JE2_T_D10_3': 1, 'JE2_T_D10_5': 1, 'JE2_T_F02_5': 1}]
2209,None,1059105-1062875:[2, {'JE2_T_D08_1': 1, 'JE2_T_D08_2': 1}]
2217,None,1065878-1067071:[12, {'JE2_T_D10_1': 1, 'JE2_T_D10_3': 1, 'JE2_T_D10_5': 1, 'JE2_T_D08_1': 1, 'JE2_T_D08_2': 1, 'JE2_T_D08_3': 1, 'JE2_T_F10_2': 1, 'JE2_T_F10_4': 1, 'JE2_T_F10_5': 1, 'JE2_T_F02_5': 1, 'JE2_T_F04_3': 1, 'JE2_T_F04_5': 1}]
2259,None,1086631-1088031:[2, {'JE2_T_F04_3': 1, 'JE2_T_F04_5': 1}]
2511,None,1199347-1199910:[1, {'JE2_T_F02_5': 1}]
2657,None,1278360-1278914:[3, {'JE2_T_D10_1': 1, 'JE2_T_D10_3': 1, 'JE2_T_D10_5': 1}]
2777,None,1343573-1344157:[1, {'JE2_T_D10_3': 1}]
3059,None,1471697-1502962:[1, {'JE2_T_D08_2': 1}]
3613,None,1745092-1745610:[3, {'JE2_T_F02_5': 1, 'JE2_T_F04_3': 1, 'JE2_T_F04_5': 1}]
3709,None,1788753-1789223:[3, {'JE2_T_D10_1': 1, 'JE2_T_D10_3': 1, 'JE2_T_D10_5': 1}]
3801,None,1841625-1842899:[5, {'JE2_T_D08_3': 1, 'JE2_T_F10_2': 1, 'JE2_T_F10_4': 1, 'JE2_T_F10_5': 1, 'JE2_T_F10_3': 1}]
3863,None,1876143-1877804:[1, {'JE2_T_F04_3': 1}]
4777,None,2231991-2232515:[1, {'JE2_T_D08_1': 1}]
5773,None,2693722-2694270:[1, {'JE2_T_F04_5': 1}]


#Cluster 2 (37):
30,None,17802-19769:[6, {'JE2_T_D10_2': 1, 'JE2_T_D10_4': 1, 'JE2_T_F10_1': 1, 'JE2_T_F02_2': 1, 'JE2_T_F02_3': 1, 'JE2_T_F04_4': 1}]
176,None,88849-90600:[1, {'JE2_T_F02_1': 1}]
418,None,219020-219577:[1, {'JE2_T_F02_2': 1}]
674,None,355722-357029:[4, {'JE2_S_B06_1': 2, 'JE2_S_B06_5': 2}]
998,None,504434-505861:[3, {'JE2_S_D04_1': 1, 'JE2_S_D04_2': 1, 'JE2_S_D04_4': 1}]
1060,None,531927-532751:[1, {'JE2_T_F02_1': 1}]
1276,None,637380-638780:[1, {'JE2_T_F02_1': 1}]
1500,None,733905-734579:[1, {'JE2_T_F02_3': 1}]
1686,None,820111-820431:[3, {'JE2_T_F02_1': 1, 'JE2_T_F02_2': 1, 'JE2_T_F02_3': 1}]
2171,None,1042228-1043709:[1, {'JE2_T_F04_2': 1}]
2183,None,1046814-1047752:[1, {'JE2_T_D10_4': 1}]
2189,None,1049282-1050955:[1, {'JE2_S_B06_1': 1}]
2217,None,1065878-1067071:[9, {'JE2_T_D10_2': 1, 'JE2_T_D10_4': 1, 'JE2_T_F10_1': 1, 'JE2_T_F02_1': 1, 'JE2_T_F02_2': 1, 'JE2_T_F02_3': 1, 'JE2_T_F04_1': 1, 'JE2_T_F04_2': 1, 'JE2_T_F04_4': 1}]
2247,None,1079731-1081215:[1, {'JE2_T_F02_1': 1}]
2259,None,1086631-1088031:[3, {'JE2_T_F04_1': 1, 'JE2_T_F04_2': 1, 'JE2_T_F04_4': 1}]
2312,None,1109443-1110537:[1, {'JE2_T_F02_1': 1}]
2657,None,1278360-1278914:[1, {'JE2_T_D10_2': 1}]
2733,None,1321537-1324155:[3, {'JE2_T_F02_1': 1, 'JE2_T_F02_2': 1, 'JE2_T_F02_3': 1}]
2735,None,1324168-1326177:[3, {'JE2_T_F02_1': 1, 'JE2_T_F02_2': 1, 'JE2_T_F02_3': 1}]
2861,None,1374097-1374564:[1, {'JE2_T_F02_2': 1}]
2891,None,1391705-1393165:[1, {'JE2_T_F02_2': 1}]
3037,None,1464143-1464676:[1, {'JE2_T_F02_1': 1}]
3393,None,1645009-1645473:[1, {'JE2_T_D10_4': 1}]
3470,None,1677802-1679193:[2, {'JE2_S_B06_1': 1, 'JE2_S_B06_5': 1}]
3514,None,1698728-1699702:[1, {'JE2_T_F04_4': 1}]
3613,None,1745092-1745610:[3, {'JE2_T_F04_1': 1, 'JE2_T_F04_2': 1, 'JE2_T_F04_4': 1}]
3681,None,1776200-1777462:[7, {'JE2_S_B06_1': 2, 'JE2_S_B06_5': 2, 'JE2_S_D04_1': 1, 'JE2_S_D04_2': 1, 'JE2_S_D04_4': 1}]
3801,None,1841625-1842899:[1, {'JE2_T_F10_1': 1}]
4063,None,1964399-1965799:[1, {'JE2_T_F02_2': 1}]
4111,None,1987481-1987876:[1, {'JE2_T_F02_2': 1}]
4555,None,2134468-2135313:[1, {'JE2_T_F02_1': 1}]
4702,None,2201515-2202210:[1, {'JE2_T_F02_1': 1}]
5250,None,2444473-2445786:[2, {'JE2_S_B06_1': 1, 'JE2_S_B06_5': 1}]
5307,None,2472786-2473433:[1, {'JE2_T_D10_4': 1}]
5441,None,2535968-2536747:[3, {'JE2_S_D04_1': 1, 'JE2_S_D04_2': 1, 'JE2_S_D04_4': 1}]
5773,None,2693722-2694270:[1, {'JE2_T_F04_1': 1}]
6009,None,2821643-2822002:[2, {'JE2_S_B06_1': 1, 'JE2_S_B06_5': 1, 'JE2_T_F02_2': 1}]


#Cluster 3 (14):
30,None,17802-19769:[2, {'JE2_T_D08_4': 1, 'JE2_T_D08_5': 1}]
1038,None,522474-523277:[2, {'JE2_S_D04_3': 1, 'JE2_S_D04_5': 1}]
1060,None,531927-532751:[1, {'JE2_T_F02_4': 1}]
1672,None,814834-815595:[1, {'JE2_T_D08_5': 1}]
1686,None,820111-820431:[1, {'JE2_T_F02_4': 1}]
1800,None,874035-876836:[11, {'JE2_T_D08_5': 11}]
2217,None,1065878-1067071:[4, {'JE2_S_D04_3': 1, 'JE2_T_D08_4': 1, 'JE2_T_D08_5': 1, 'JE2_T_F02_4': 1}]
2733,None,1321537-1324155:[1, {'JE2_T_F02_4': 1}]
2735,None,1324168-1326177:[1, {'JE2_T_F02_4': 1}]
3464,None,1674155-1675954:[1, {'JE2_S_B10_4': 1}]
3613,None,1745092-1745610:[1, {'JE2_T_D08_5': 1}]
3908,None,1904779-1905633:[2, {'JE2_S_B10_4': 1, 'JE2_S_B10_5': 1}]
4702,None,2201515-2202210:[1, {'JE2_T_F02_4': 1}]
5441,None,2535968-2536747:[3, {'JE2_S_B04_3': 1, 'JE2_S_B06_2': 1, 'JE2_S_B06_4': 1}]


#Cluster 4 (9):
192,None,95468-96157:[1, {'JE2_S_B04_5': 1}]
264,None,135666-136676:[1, {'JE2_S_B10_1': 1}]
406,None,212100-212579:[1, {'JE2_S_B04_1': 1}]
1915,None,916783-918180:[1, {'JE2_S_B04_2': 1}]
2645,None,1274537-1275310:[3, {'JE2_S_D02_2': 1, 'JE2_S_D02_4': 1, 'JE2_S_D02_5': 1}]
2715,None,1312476-1314035:[1, {'JE2_S_B04_1': 1}]
2891,None,1391705-1393165:[1, {'JE2_S_D02_1': 1}]
3059,None,1471697-1502962:[1, {'JE2_S_B10_3': 1}]
5441,None,2535968-2536747:[1, {'JE2_S_B10_3': 1}]


#Unique to Cluster 1 (11):
250,None,128392-129918: [3, {'JE2_T_D10_1': 1, 'JE2_T_D10_3': 1, 'JE2_T_D10_5': 1}]
442,None,233920-235032: [1, {'JE2_T_D08_2': 1}]
1474,None,723018-723815: [1, {'JE2_T_D08_1': 1}]
1620,None,789860-790570: [1, {'JE2_T_F04_5': 1}]
2041,None,980328-981197: [1, {'JE2_T_D10_1': 1}]
2209,None,1059105-1062875: [2, {'JE2_T_D08_1': 1, 'JE2_T_D08_2': 1}]
2511,None,1199347-1199910: [1, {'JE2_T_F02_5': 1}]
2777,None,1343573-1344157: [1, {'JE2_T_D10_3': 1}]
3709,None,1788753-1789223: [3, {'JE2_T_D10_1': 1, 'JE2_T_D10_3': 1, 'JE2_T_D10_5': 1}]
3863,None,1876143-1877804: [1, {'JE2_T_F04_3': 1}]
4777,None,2231991-2232515: [1, {'JE2_T_D08_1': 1}]


#Unique to Cluster 2 (22):
176,None,88849-90600: [1, {'JE2_T_F02_1': 1}]
418,None,219020-219577: [1, {'JE2_T_F02_2': 1}]
674,None,355722-357029: [4, {'JE2_S_B06_1': 2, 'JE2_S_B06_5': 2}]
998,None,504434-505861: [3, {'JE2_S_D04_1': 1, 'JE2_S_D04_2': 1, 'JE2_S_D04_4': 1}]
1276,None,637380-638780: [1, {'JE2_T_F02_1': 1}]
1500,None,733905-734579: [1, {'JE2_T_F02_3': 1}]
2183,None,1046814-1047752: [1, {'JE2_T_D10_4': 1}]
2189,None,1049282-1050955: [1, {'JE2_S_B06_1': 1}]
2247,None,1079731-1081215: [1, {'JE2_T_F02_1': 1}]
2312,None,1109443-1110537: [1, {'JE2_T_F02_1': 1}]
2861,None,1374097-1374564: [1, {'JE2_T_F02_2': 1}]
3037,None,1464143-1464676: [1, {'JE2_T_F02_1': 1}]
3393,None,1645009-1645473: [1, {'JE2_T_D10_4': 1}]
3470,None,1677802-1679193: [2, {'JE2_S_B06_1': 1, 'JE2_S_B06_5': 1}]
3514,None,1698728-1699702: [1, {'JE2_T_F04_4': 1}]
3681,None,1776200-1777462: [7, {'JE2_S_B06_1': 2, 'JE2_S_B06_5': 2, 'JE2_S_D04_1': 1, 'JE2_S_D04_2': 1, 'JE2_S_D04_4': 1}]
4063,None,1964399-1965799: [1, {'JE2_T_F02_2': 1}]
4111,None,1987481-1987876: [1, {'JE2_T_F02_2': 1}]
4555,None,2134468-2135313: [1, {'JE2_T_F02_1': 1}]
5250,None,2444473-2445786: [2, {'JE2_S_B06_1': 1, 'JE2_S_B06_5': 1}]
5307,None,2472786-2473433: [1, {'JE2_T_D10_4': 1}]
6009,None,2821643-2822002: [2, {'JE2_S_B06_1': 1, 'JE2_S_B06_5': 1, 'JE2_T_F02_2': 1}]


#Unique to Cluster 3 (5):
1038,None,522474-523277: [2, {'JE2_S_D04_3': 1, 'JE2_S_D04_5': 1}]
1672,None,814834-815595: [1, {'JE2_T_D08_5': 1}]
1800,None,874035-876836: [11, {'JE2_T_D08_5': 11}]
3464,None,1674155-1675954: [1, {'JE2_S_B10_4': 1}]
3908,None,1904779-1905633: [2, {'JE2_S_B10_4': 1, 'JE2_S_B10_5': 1}]


#Unique to Cluster 4 (6):
192,None,95468-96157: [1, {'JE2_S_B04_5': 1}]
264,None,135666-136676: [1, {'JE2_S_B10_1': 1}]
406,None,212100-212579: [1, {'JE2_S_B04_1': 1}]
1915,None,916783-918180: [1, {'JE2_S_B04_2': 1}]
2645,None,1274537-1275310: [3, {'JE2_S_D02_2': 1, 'JE2_S_D02_4': 1, 'JE2_S_D02_5': 1}]
2715,None,1312476-1314035: [1, {'JE2_S_B04_1': 1}]


#Common (0):

```


```{r}
df<- structure(list(X1 = c(37L, 2L, 3L, 4L, 5L, 6L, 7L, 8L, 9L, NA, 
11L, 12L), X2 = c(40L, NA, 35L, 35L, 35L, 34L, 29L, 28L, 28L, 
NA, 25L, 24L), X3 = c(60L, 44L, 49L, 41L, NA, NA, NA, 25L, 26L, 
NA, NA, 22L), T1 = c(19L, 55L, 47L, 46L, 36L, 42L, 25L, NA, 33L, 
42L, 50L, 22L), T2 = c(75L, NA, 32L, 44L, 27L, 31L, 17L, NA, 
18L, 45L, 10L, 11L), T3 = c(5L, 6L, 7L, 8L, 9L, 10L, 11L, NA, 
46L, 36L, 42L, NA), P1 = c(2L, 2L, 3L, 4L, 2L, 6L, 7L, 8L, 9L, 
NA, 1L, 12L), P2 = c(40L, 44L, 4L, 2L, 1L, 1L, 29L, 1L, 1L, 1L, 
5L, 55L), P3 = c(1L, 44L, 49L, 3L, NA, NA, NA, 25L, 26L, NA, 
NA, 66L)), class = "data.frame", row.names = c(NA, -12L))
```

